# in workers/wrangler.toml
name = "b2b-image-handler"
main = "src/image-handler.js" # Aangepast pad
compatibility_date = "2023-10-30"

[[r2_buckets]]
binding = "IMAGE_BUCKET"
bucket_name = "motordash"